### ISSUE TITLE
Non ASCII characters

### ISSUE THREAD

**Issue by MatheMax** [imbi-heidelberg/DescrTab#37]
Hey @jan-imbi 
can we avoid the Umlaut here or is it necessary?

https://github.com/imbi-heidelberg/DescrTab/blob/3f591fb51e877e060642b0172006f69be53d85e7/R/des.print.R#L435-L438

**Comment by jan-imbi** [comment]
Ich _vermute_ man kann (Textkörper) einfach löschen.

**Comment by jan-imbi** [comment]
Werde es morgen versuchen.

**Comment by MatheMax** [comment]
cf. #39
