### ISSUE TITLE
Error in tabulating factor variables?

### ISSUE THREAD

**Issue by s-kilian** [imbi-heidelberg/DescrTab#8]
The command
`DescrTab::des.print(iris, create = "R")`
gives the error
`Error in descr(dat, group, var.names, percent.vertical, data.names, nonparametric,  : 
  argument "var.names" is missing, with no default`
This seems to be caused by the factor variable Species in the iris data, as excluding this variable works fine:
`DescrTab::des.print(select(iris, -Species), create = "R")`

I often created tables from variables coded as factor in the past and never encountered this problem, so it seems to be caused by some new changes.

**Comment by MatheMax** [comment]
Done with #17
